language: generic

sudo: required

services: 
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t prashanth1261/dockercomplex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true prashanth1261/dockercomplex npm run test -- --coverage

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t prashanth1261/multi-client ./client
  - docker build -t prashanth1261/multi-nginx ./nginx
  - docker build -t prashanth1261/multi-server ./server
  - docker build -t prashanth1261/multi-worker ./worker
  - docker push prashanth1261/multi-client
  - docker push prashanth1261/multi-nginx
  - docker push prashanth1261/multi-server
  - docker push prashanth1261/multi-worker